/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myuniversty;

import java.awt.ComponentOrientation;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SCC
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Course
     */
    int choose;
    Connection con=null;
    PreparedStatement com=null;
    ResultSet rst=null;
    private String sem;
    public Course() {
        initComponents();
        RightToLeft();
        
        InsertNameDoctor();
        
        
    
        
     choose = MainMenu.chC;
     if(choose==2){
         this.setTitle("تعديل المادة");
//         addAndUpdateAndDelete.setIcon(null);
         name.setEnabled(false);
         salary.setEnabled(false);
         hours.setEnabled(false);
         doctor.setEnabled(false);
         first.setEnabled(false);
         seconds.setEnabled(false);
     }else if(choose==3){
         this.setTitle("حذف المادة");
//              addAndUpdateAndDelete.setIcon(null);
         name.setEnabled(false);
         salary.setEnabled(false);
         hours.setEnabled(false);
         doctor.setEnabled(false);
         first.setEnabled(false);
         seconds.setEnabled(false);
     }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        doctor = new javax.swing.JComboBox();
        first = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        addAndUpdateAndDelete = new javax.swing.JButton();
        seconds = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("أضافة مادة");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("رقم المادة");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 20));

        id.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم المادة");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 20));

        hours.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("عدد الساعات");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 20));

        salary.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        doctor.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        first.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(first);
        first.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        first.setForeground(new java.awt.Color(255, 255, 255));
        first.setText("الأول");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("خروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addAndUpdateAndDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addAndUpdateAndDelete.setText("أضافة");
        addAndUpdateAndDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAndUpdateAndDeleteActionPerformed(evt);
            }
        });

        seconds.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(seconds);
        seconds.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        seconds.setForeground(new java.awt.Color(255, 255, 255));
        seconds.setText("الثاني");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("الفصل الدراسي");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("دكتور المادة");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("سعر المادة");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addAndUpdateAndDelete)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(seconds)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(first)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))))
                        .addGap(27, 27, 27))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(first)
                            .addComponent(seconds)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAndUpdateAndDelete)
                            .addComponent(jButton1))
                        .addGap(38, 38, 38))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        setSize(new java.awt.Dimension(415, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addAndUpdateAndDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAndUpdateAndDeleteActionPerformed
        // TODO add your handling code here:
        if(choose==1){
            Insert(); 
        }else if(choose==2){
            Update();
        }else{
            Delete();
        }
    }//GEN-LAST:event_addAndUpdateAndDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAndUpdateAndDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox doctor;
    private javax.swing.JRadioButton first;
    private javax.swing.JTextField hours;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField salary;
    private javax.swing.JRadioButton seconds;
    // End of variables declaration//GEN-END:variables

    private void RightToLeft() {
   id.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   hours.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   salary.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   first.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   seconds.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   this.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    private void InsertNameDoctor() {
    doctor.setSelectedIndex(-1);
        try {
            con = ConnectionDataBase.Connet();
            com = con.prepareStatement("select nameD from Doctor");
            rst = com.executeQuery();
            
            while(rst.next()){
                doctor.addItem(rst.getString("nameD"));
            }    doctor.setSelectedIndex(-1);
        } catch (SQLException ex) {
        }finally{
                 try {
                     con.close();
                 } catch (SQLException ex) {
                 }
             }
        
     
    }

    private void Insert() {
         String miss = "لقد نسيك ادخال البيانات التاليه"+"\n";
      if(id.getText().equals("")){
          miss+="رقم المادة"+"\n";
      }
      if(name.getText().equals("")){
          miss+="اسم المادة"+"\n";
      }
      if(hours.getText().equals("")){
          miss+="عدد ساعات المادة"+"\n";
      }
      if(salary.getText().equals("")){
          miss+="سعر المادةالواحدة"+"\n";
      }
      if(doctor.getSelectedIndex()==-1){
          miss+="دكتور المادة"+"\n";
      }
      if(!first.isSelected()&&!seconds.isSelected()){
          miss+="الفصل الدراسي"+"\n";
      }
      int sem=1;
      if(seconds.isSelected()){
          sem=2;
      }
      if(!id.getText().equals("")&&!name.getText().equals("")&&!hours.getText().equals("")&&!salary.getText().equals("")&&doctor.getSelectedIndex()!=-1&&(first.isSelected()||seconds.isSelected())){
             try {
                 con=ConnectionDataBase.Connet();
                 com=con.prepareStatement("salact*from Course where idCourse='"+Integer.parseInt(id.getText())+"'");
                 rst=com.executeQuery();
                 
                 if(!rst.next()){
                     com = con.prepareStatement("Insert into Course values('"+Integer.parseInt(id.getText())+"','"+name.getText()+"','"+Integer.parseInt(hours.getText())+"','"+doctor.getSelectedItem()+"','"+Integer.parseInt(salary.getText())+"','"+sem+"')");
                     com.execute();
                     JOptionPane.showMessageDialog(null, "تم اضافة المادة بنجاح","تمت الاضافة",JOptionPane.INFORMATION_MESSAGE);
                     Clear();
                 }else{
                  JOptionPane.showMessageDialog(null,"رقم المادة موجود مسبقا","موجود",2);
                 }
                 
                 
             } catch (SQLException ex) {
             }finally{
                 try {
                     con.close();
                 } catch (SQLException ex) {
                 }
             }
      }
      else{
              JOptionPane.showMessageDialog(null,miss,"فقد بيانات الدخول",2);    
  
      }
      

    }

    private void Update() {
                 String miss = "لقد نسيك ادخال البيانات التاليه"+"\n";
      
      if(name.getText().equals("")){
          miss+="اسم المادة"+"\n";
      }
      if(hours.getText().equals("")){
          miss+="عدد ساعات المادة"+"\n";
      }
      if(salary.getText().equals("")){
          miss+="سعر المادةالواحدة"+"\n";
      }
      if(doctor.getSelectedIndex()==-1){
          miss+="دكتور المادة"+"\n";
      }
      if(!first.isSelected()&&!seconds.isSelected()){
          miss+="الفصل الدراسي"+"\n";
      }
        if(!name.getText().equals("")&&!hours.getText().equals("")&&(first.isSelected()||seconds.isSelected())){
          
      }
      else{
              JOptionPane.showMessageDialog(null,miss,"فقد بيانات الدخول",2);    
  
      }
      
    }

    private void Delete() {
          String miss = "لقد نسيك ادخال البيانات التاليه"+"\n";
      if(id.getText().equals("")){
          miss+="رقم المادة"+"\n";
      }
           if(!id.getText().equals("")){
                     try {
                 con=ConnectionDataBase.Connet();
                 com=con.prepareStatement("salact*from Course where idCourse='"+Integer.parseInt(id.getText())+"'");
                 rst=com.executeQuery();
                 if(rst.next()){
                     
                 }else{
                  JOptionPane.showMessageDialog(null,"رقم المادة غير موجود مسبقا","غير موجود",2);
                 }
                 
                 
             } catch (SQLException ex) {
             }finally{
                 try {
                     con.close();
                 } catch (SQLException ex) {
                 }
             }
          
      }
      else{
              JOptionPane.showMessageDialog(null,miss,"فقد بيانات الدخول",2);    
  
      }
      
      
    }

    private void Clear() {
     id.setText("");
     name.setText("");
     salary.setText("");
     hours.setText("");
     doctor.setSelectedIndex(-1);
    }

    
}
