/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myuniversty;

import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author SCC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String id="";
    String user="";
    
    Connection con=null;
    PreparedStatement com=null;
    ResultSet rst= null;
    private String password;
    public Login() {
        initComponents();
        this.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jMenu1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        file.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        h1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        login.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        exit.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
//        changeStyle.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s3.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s4.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s5.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s6.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s7.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        help.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        my.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        idOrName.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        pass.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jCheckBox1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        selectPerson.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        passLable = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();
        seleCtPersolable = new javax.swing.JLabel();
        idOrName = new javax.swing.JTextField();
        selectPerson = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        Miss = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        file = new javax.swing.JMenuItem();
        h1 = new javax.swing.JMenuItem();
        login = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();
        s1 = new javax.swing.JMenuItem();
        s2 = new javax.swing.JMenuItem();
        s3 = new javax.swing.JMenuItem();
        s4 = new javax.swing.JMenuItem();
        s5 = new javax.swing.JMenuItem();
        s6 = new javax.swing.JMenuItem();
        s7 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        my = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تسجيل الدخول ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(616, 231));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/image/شخصي.PNG"))); // NOI18N

        passLable.setBackground(new java.awt.Color(0, 255, 204));
        passLable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        passLable.setForeground(new java.awt.Color(255, 255, 255));
        passLable.setText("كلمة المرور");

        idLable.setBackground(new java.awt.Color(0, 204, 204));
        idLable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        idLable.setForeground(new java.awt.Color(255, 255, 255));
        idLable.setText("رقم التعريف");

        seleCtPersolable.setBackground(new java.awt.Color(0, 255, 204));
        seleCtPersolable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seleCtPersolable.setForeground(new java.awt.Color(255, 255, 255));
        seleCtPersolable.setText("تحديد الشخص");

        selectPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "الادارة", "دكتور", "طالب" }));
        selectPerson.setSelectedIndex(-1);
        selectPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectPersonItemStateChanged(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(0, 51, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("اظهر كلمة المرور");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        Miss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Miss.setText("دخول");
        Miss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("خروج");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Miss)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(passLable)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idOrName)
                                .addComponent(selectPerson, 0, 183, Short.MAX_VALUE)
                                .addComponent(pass)))
                        .addGap(20, 20, 20)
                        .addComponent(seleCtPersolable)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seleCtPersolable)
                            .addComponent(selectPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLable)
                            .addComponent(idOrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLable)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Miss)
                            .addComponent(jButton2)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("لوحة تسجيل الدخول");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("ملف");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        file.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        file.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        file.setText("دخول");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        jMenu1.add(file);

        h1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        h1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h1.setText("خروج");
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        jMenu1.add(h1);

        jMenuBar1.add(jMenu1);

        login.setText("مساعد");
        login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        exit.setText("تغير الستايل");
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        s1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s1.setText("أصفر");
        exit.add(s1);

        s2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s2.setText("رمادي");
        exit.add(s2);

        s3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s3.setText("أزرق");
        exit.add(s3);

        s4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s4.setText("رمادي-فضي");
        exit.add(s4);

        s5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s5.setText("فضي");
        exit.add(s5);

        s6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s6.setText("أسود");
        exit.add(s6);

        s7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s7.setText("نظام التشغيل");
        exit.add(s7);

        login.add(exit);

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        help.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        help.setText("مساعدة");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        login.add(help);

        my.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        my.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        my.setText("عني");
        my.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myActionPerformed(evt);
            }
        });
        login.add(my);

        jMenuBar1.add(login);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(672, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
// TODO add your handling code here:
        
        if(jCheckBox1.isSelected()){
            pass.setEchoChar((char)0);
        }else{
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void myActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myActionPerformed
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_myActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_h1ActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(rootPane,"عذرا غير فعال الان");
    }//GEN-LAST:event_helpActionPerformed

    private void MissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissActionPerformed
        // TODO add your handling code here:
        String miss= "لقد نسيك ادخال البيانات التاليه"+"\n";
       if(idOrName.getText().equals("")){
       miss+=seleCtPersolable.getText()+"\n";
          }
    if(pass.getText().equals("")){
     miss+=idLable.getText()+"\n";
    }
    if(selectPerson.getSelectedIndex()==-1){
        miss+=passLable.getText()+"\n";
    }
    
    if(!idOrName.getText().equals("")&& !pass.getText().equals("")&& selectPerson.getSelectedIndex()!=-1){
        
    if(selectPerson.getSelectedIndex()==0){ 
        AdminLogin();
    }
    else if(selectPerson.getSelectedIndex()==1){
        DoctorLogin();
    }
    else if(selectPerson.getSelectedIndex()==2){
        StudentLogin();
    }
    }
    else{
        JOptionPane.showMessageDialog(null,miss,"فقد البيانات",2);
       
    }
        
    }//GEN-LAST:event_MissActionPerformed

    private void selectPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectPersonItemStateChanged
        // TODO add your handling code here:
        if(selectPerson.getSelectedIndex()==0){
        idLable.setText("اسم المستخدم");
    }
    else if(selectPerson.getSelectedIndex()==1||selectPerson.getSelectedIndex()==2){
        
       idLable.setText("رقم التعريف");
    }
    }//GEN-LAST:event_selectPersonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Miss;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuItem file;
    private javax.swing.JMenuItem h1;
    private javax.swing.JMenuItem help;
    private javax.swing.JLabel idLable;
    private javax.swing.JTextField idOrName;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu login;
    private javax.swing.JMenuItem my;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passLable;
    private javax.swing.JMenuItem s1;
    private javax.swing.JMenuItem s2;
    private javax.swing.JMenuItem s3;
    private javax.swing.JMenuItem s4;
    private javax.swing.JMenuItem s5;
    private javax.swing.JMenuItem s6;
    private javax.swing.JMenuItem s7;
    private javax.swing.JLabel seleCtPersolable;
    private javax.swing.JComboBox selectPerson;
    // End of variables declaration//GEN-END:variables

    private void AdminLogin() {
        
    user = idOrName.getText().trim();
    String Password = pass.getText().trim();
    
    if(user.equals("admin")&&Password.equals("123456")){
     MainMenu mainMenu = new MainMenu();
     mainMenu.D.setEnabled(false);
     mainMenu.S.setEnabled(false);
     mainMenu.setVisible(true);
     this.setVisible(false);
     JOptionPane.showMessageDialog(null,"مرحبا"+user);
    }else{
      JOptionPane.showMessageDialog(null, "تاكد من صحة البيانات المدخلة","معلومات خاطئة",JOptionPane.ERROR_MESSAGE);
    }
        
    }

    private void DoctorLogin() {
    id = idOrName.getText().trim();
    String password = pass.getText().trim();
        
        try {
            con = ConnectionDataBase.Connet();
            com = con.prepareStatement(" select*from Doctor where id="+Integer.parseInt(id)+" and password="+password+" ");
            rst = com.executeQuery();
            
            if(rst.next()){
                 user = rst.getString("nameD");
                
     MainMenu mainMenu = new MainMenu();
     mainMenu.A.setEnabled(false);
     mainMenu.S.setEnabled(false);
     mainMenu.setVisible(true);
     this.setVisible(false);
     JOptionPane.showMessageDialog(null,"مرحبا دكتور"+user);
                
            }
            else{
          JOptionPane.showMessageDialog(null, "تاكد من صحة البيانات المدخلة","معلومات خاطئة",JOptionPane.ERROR_MESSAGE);        
                }
            
        } catch (SQLException ex) {
        
        
        }finally{
        try {
            con.close();
        } catch (SQLException ex) {
          
        }
        }
       
    }

    private void StudentLogin() {
        id = idOrName.getText().trim();
    String password = pass.getText().trim();
        
        try {
            con = ConnectionDataBase.Connet();
            com = con.prepareStatement(" select*from Student where id="+Integer.parseInt(id)+" and password="+password+" ");
            rst = com.executeQuery();
            
            if(rst.next()){
                 user = rst.getString("nameS");
                
     MainMenu mainMenu = new MainMenu();
     mainMenu.A.setEnabled(false);
     mainMenu.D.setEnabled(false);
     mainMenu.setVisible(true);
     this.setVisible(false);
     JOptionPane.showMessageDialog(null,"مرحبا "+user);
                
            }
            else{
          JOptionPane.showMessageDialog(null, "تاكد من صحة البيانات المدخلة","معلومات خاطئة",JOptionPane.ERROR_MESSAGE);        
                }
            
        } catch (SQLException ex) {
        
        
        }finally{
        try {
            con.close();
        } catch (SQLException ex) {
          
        }
        }

    }
}
