/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myuniversty;

import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.joni.exception.JOniException;

/**
 *
 * @author SCC
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    public static int ch;
        static int chC;
        static int chD;
        public static int changePassS_D;

    public MainMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_HORIZ);
        RightToLeft();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        A = new javax.swing.JMenu();
        student = new javax.swing.JMenu();
        addS = new javax.swing.JMenuItem();
        UpdateS = new javax.swing.JMenuItem();
        DeleteS = new javax.swing.JMenuItem();
        Doctor = new javax.swing.JMenu();
        addD = new javax.swing.JMenuItem();
        UpdateD = new javax.swing.JMenuItem();
        DeleteD = new javax.swing.JMenuItem();
        course = new javax.swing.JMenu();
        addC = new javax.swing.JMenuItem();
        UpdateC = new javax.swing.JMenuItem();
        DeleteC = new javax.swing.JMenuItem();
        M = new javax.swing.JMenuItem();
        n = new javax.swing.JMenuItem();
        V = new javax.swing.JMenuItem();
        D = new javax.swing.JMenu();
        Q = new javax.swing.JMenuItem();
        W = new javax.swing.JMenuItem();
        R = new javax.swing.JMenuItem();
        T = new javax.swing.JMenuItem();
        S = new javax.swing.JMenu();
        P = new javax.swing.JMenuItem();
        O = new javax.swing.JMenuItem();
        I = new javax.swing.JMenuItem();
        U = new javax.swing.JMenuItem();
        Y = new javax.swing.JMenuItem();
        H = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();
        s1 = new javax.swing.JMenuItem();
        s2 = new javax.swing.JMenuItem();
        s3 = new javax.swing.JMenuItem();
        s4 = new javax.swing.JMenuItem();
        s5 = new javax.swing.JMenuItem();
        s6 = new javax.swing.JMenuItem();
        s7 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        my = new javax.swing.JMenuItem();
        L = new javax.swing.JMenu();
        LogOff = new javax.swing.JMenuItem();

        jMenu8.setText("jMenu8");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/image/ur.JPG"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1197, 700));

        A.setText("الادارة");
        A.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        student.setText("طلاب");
        student.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        addS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addS.setText("اضافة طالب");
        addS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSActionPerformed(evt);
            }
        });
        student.add(addS);

        UpdateS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateS.setText("تعديل طالب");
        UpdateS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSActionPerformed(evt);
            }
        });
        student.add(UpdateS);

        DeleteS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteS.setText("حذف طالب");
        DeleteS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSActionPerformed(evt);
            }
        });
        student.add(DeleteS);

        A.add(student);

        Doctor.setText("دكتور");
        Doctor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        addD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addD.setText("اضافة دكتور");
        addD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDActionPerformed(evt);
            }
        });
        Doctor.add(addD);

        UpdateD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateD.setText("تعديل دكتور");
        UpdateD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDActionPerformed(evt);
            }
        });
        Doctor.add(UpdateD);

        DeleteD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteD.setText("حذف دكتور");
        DeleteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDActionPerformed(evt);
            }
        });
        Doctor.add(DeleteD);

        A.add(Doctor);

        course.setText("كورس");
        course.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        addC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addC.setText("اضافة كورس");
        addC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCActionPerformed(evt);
            }
        });
        course.add(addC);

        UpdateC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateC.setText("تعديل كورس");
        UpdateC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCActionPerformed(evt);
            }
        });
        course.add(UpdateC);

        DeleteC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteC.setText("حذف كورس");
        DeleteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCActionPerformed(evt);
            }
        });
        course.add(DeleteC);

        A.add(course);

        M.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        M.setText("تحديد الفصل الدرسي");
        A.add(M);

        n.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n.setText("تسديد الرسوم");
        A.add(n);

        V.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        V.setText("تسجيل او حذف كورس لطالب");
        A.add(V);

        jMenuBar1.add(A);

        D.setText("الدكتور");
        D.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Q.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Q.setText("الملف الشخصي");
        D.add(Q);

        W.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        W.setText("عرض الطلاب المسجلين للمادة");
        D.add(W);

        R.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        R.setText("اضافة العلامات");
        D.add(R);

        T.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        T.setText("تغير كلمة السر");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        D.add(T);

        jMenuBar1.add(D);

        S.setText("الطالب");
        S.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        P.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        P.setText("الملف الشخصي");
        S.add(P);

        O.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        O.setText("تسجيل كورس");
        S.add(O);

        I.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        I.setText("كشف الدرجات");
        S.add(I);

        U.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        U.setText("المعدل التراكمي");
        S.add(U);

        Y.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Y.setText("تغير كلمة السر");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        S.add(Y);

        jMenuBar1.add(S);

        H.setText("مساعدة");
        H.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        exit.setText("تغير الستايل");
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        s1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s1.setText("أصفر");
        exit.add(s1);

        s2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s2.setText("رمادي");
        exit.add(s2);

        s3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s3.setText("أزرق");
        exit.add(s3);

        s4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s4.setText("رمادي-فضي");
        exit.add(s4);

        s5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s5.setText("فضي");
        exit.add(s5);

        s6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s6.setText("أسود");
        exit.add(s6);

        s7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s7.setText("نظام التشغيل");
        exit.add(s7);

        H.add(exit);

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        help.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        help.setText("مساعدة");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        H.add(help);

        my.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        my.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        my.setText("عني");
        my.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myActionPerformed(evt);
            }
        });
        H.add(my);

        jMenuBar1.add(H);

        L.setText("تسجيل الخروج");
        L.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        LogOff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogOff.setText("تسجيل الخروج");
        LogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOffActionPerformed(evt);
            }
        });
        L.add(LogOff);

        jMenuBar1.add(L);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myActionPerformed
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_myActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"عذرا غير فعال الان");
    }//GEN-LAST:event_helpActionPerformed

    private void LogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOffActionPerformed
        // TODO add your handling code here:
        try{
            Thread.sleep(500);
            
        }catch(Exception e){
            
        }
        Login login=new Login();
        login.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_LogOffActionPerformed

    private void addSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSActionPerformed
        // TODO add your handling code here:
        ch=1;
       Student s =new Student();
       s.setVisible(true);
       
       
    }//GEN-LAST:event_addSActionPerformed

    private void UpdateSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSActionPerformed
        // TODO add your handling code here:
        ch=2;
        Student s =new Student();
       s.setVisible(true);
      
       
    }//GEN-LAST:event_UpdateSActionPerformed

    private void DeleteSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSActionPerformed
        // TODO add your handling code here:
        ch=3;
        Student s =new Student();
       s.setVisible(true);
       
    }//GEN-LAST:event_DeleteSActionPerformed

    private void UpdateCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCActionPerformed
        // TODO add your handling code here:
        chC=2;
        new Course().setVisible(true);
    }//GEN-LAST:event_UpdateCActionPerformed

    private void addCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCActionPerformed
        // TODO add your handling code here:
        chC=1;
        new Course().setVisible(true);
    }//GEN-LAST:event_addCActionPerformed

    private void DeleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCActionPerformed
        // TODO add your handling code here:
        chC=3;
        new Course().setVisible(true);
    }//GEN-LAST:event_DeleteCActionPerformed

    private void addDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDActionPerformed
        // TODO add your handling code here:
        chD =1;
        new Doctor().setVisible(true);
    }//GEN-LAST:event_addDActionPerformed

    private void UpdateDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDActionPerformed
        // TODO add your handling code here:
        chD=2;
        new Doctor().setVisible(true);
    }//GEN-LAST:event_UpdateDActionPerformed

    private void DeleteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDActionPerformed
        // TODO add your handling code here:
        chD=3;
        new Doctor().setVisible(true);
    }//GEN-LAST:event_DeleteDActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        ChangBassword about = new ChangBassword();
        about.setVisible(true);
    }//GEN-LAST:event_TActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        ChangBassword about = new ChangBassword();
        about.setVisible(true);
    }//GEN-LAST:event_YActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu A;
    public javax.swing.JMenu D;
    private javax.swing.JMenuItem DeleteC;
    private javax.swing.JMenuItem DeleteD;
    private javax.swing.JMenuItem DeleteS;
    private javax.swing.JMenu Doctor;
    private javax.swing.JMenu H;
    private javax.swing.JMenuItem I;
    private javax.swing.JMenu L;
    private javax.swing.JMenuItem LogOff;
    private javax.swing.JMenuItem M;
    private javax.swing.JMenuItem O;
    private javax.swing.JMenuItem P;
    private javax.swing.JMenuItem Q;
    private javax.swing.JMenuItem R;
    public javax.swing.JMenu S;
    private javax.swing.JMenuItem T;
    private javax.swing.JMenuItem U;
    private javax.swing.JMenuItem UpdateC;
    private javax.swing.JMenuItem UpdateD;
    private javax.swing.JMenuItem UpdateS;
    private javax.swing.JMenuItem V;
    private javax.swing.JMenuItem W;
    private javax.swing.JMenuItem Y;
    private javax.swing.JMenuItem addC;
    private javax.swing.JMenuItem addD;
    private javax.swing.JMenuItem addS;
    private javax.swing.JMenu course;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuItem help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem my;
    private javax.swing.JMenuItem n;
    private javax.swing.JMenuItem s1;
    private javax.swing.JMenuItem s2;
    private javax.swing.JMenuItem s3;
    private javax.swing.JMenuItem s4;
    private javax.swing.JMenuItem s5;
    private javax.swing.JMenuItem s6;
    private javax.swing.JMenuItem s7;
    private javax.swing.JMenu student;
    // End of variables declaration//GEN-END:variables

    private void RightToLeft() {
        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
       A .setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       D .setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       S .setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       H .setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       L .setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
       student.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       Doctor.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT); 
       course.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       M.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       n.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       V.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       addS.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       UpdateS.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       DeleteS.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       addD.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       UpdateD.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       DeleteD.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       addC.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       UpdateC.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       DeleteC.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       Q.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       W.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       R.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       T.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       P.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       O.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       I.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       U.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       Y.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
        exit.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s3.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s4.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s5.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s6.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        s7.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        help.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        my.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
    }
}
