    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myuniversty;

import java.awt.ComponentOrientation;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SCC
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    int choose;
    Connection con = null;
    PreparedStatement com = null;
    ResultSet rst = null;
    
    public Student() {
        initComponents();
        id.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        mobile.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        male.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        fmale.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        choose=MainMenu.ch;
        if(choose==2){
         this.setTitle("تعديل طالب");
//         addAndUpdateAndDelete.setaddAndUpdateAndDelete(new UpdateS("تعديل"));
                 name.setEnabled(false);
                 mobile.setEnabled(false);
                 male.setEnabled(false);
                 fmale.setEnabled(false);
        }
        if(choose==3){
             this.setTitle("حذف طالب");
//        addAndUpdateAndDelete.setlcon(new Imagelcon("src\\image\\تنزيل.jpg"));
                 
                 name.setEnabled(false);
                 mobile.setEnabled(false);
                 male.setEnabled(false);
                 fmale.setEnabled(false);
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fmale = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        addAndUpdateAndDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("اضافة طالب");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("رقم الطالب");

        id.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم الطالب");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("رقم الجوال");

        mobile.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("الجنس");

        fmale.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(fmale);
        fmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fmale.setForeground(new java.awt.Color(255, 255, 153));
        fmale.setText("أنثى");
        fmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmaleActionPerformed(evt);
            }
        });

        male.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 153));
        male.setText("ذكر");

        addAndUpdateAndDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addAndUpdateAndDelete.setText("أضافة");
        addAndUpdateAndDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAndUpdateAndDeleteActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("خروج");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(fmale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(male)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addAndUpdateAndDelete)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fmale)
                    .addComponent(male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAndUpdateAndDelete)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 340));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 64, 380, 130));

        setSize(new java.awt.Dimension(385, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addAndUpdateAndDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAndUpdateAndDeleteActionPerformed
        // TODO add your handling code here:
        if(choose==1){
            try {
                Insert();
            } catch (SQLException ex) {
                Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(choose==2){
            Update();
        }
        else{
            Delete();
        }
    }//GEN-LAST:event_addAndUpdateAndDeleteActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode()==evt.VK_ENTER){
       if(id.getText().equals("")){
           JOptionPane.showMessageDialog(null,"حقل رقم التعريف فارغ","فارغ",2);
       } else{
           try {
               con = ConnectionDataBase.Connet();
               com = con.prepareStatement("select*from Student where id='"+Integer.parseInt(id.getText())+"'");
               rst =com.executeQuery();
               if(rst.next()){
                   id.setEnabled(false);
                   
                   name.setText(rst.getString(2));
                   name.setEnabled(true);
                   
                   mobile.setText(rst.getString(4));
                   mobile.setEnabled(true);
                   
                   String gender=rst.getString(5);
                   
                   if(gender.equals(fmale.getText())){
                       fmale.setSelected(true);
                   }else{
                       male.setSelected(true);
                   }
                   
                   
               }else{
                   JOptionPane.showMessageDialog(null, "رقم الطالب موجود مسبقا","موجود",2);
               }
               
               
           } catch (SQLException ex) {
             
           }finally{
               try {
                   con.close();
               } catch (SQLException ex) {
                 
               }
           }
       }  
      }  
        
        
    }//GEN-LAST:event_idKeyPressed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAndUpdateAndDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fmale;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

    private void Insert() throws SQLException {
      String miss = "لقد نسيك ادخال البيانات التاليه"+"\n";
      if(id.getText().equals("")){
          miss+="رقم الطالب"+"\n";
      }
      if(name.getText().equals("")){
          miss+="اسم الطالب"+"\n";
      }
      if(mobile.getText().equals("")){
          miss+="رقم الجوال"+"\n";
      }
      if(!male.isSelected()&&!fmale.isSelected()){
          miss+="الجنس"+"\n";
      }
      String gender = male.getText();
      if(fmale.isSelected()){
          gender = fmale.getText();
      }
      if(!id.getText().equals("")&&!name.getText().equals("")&&!mobile.getText().equals("")&&(male.isSelected()||fmale.isSelected())){
          try {
              con = ConnectionDataBase.Connet();
              com = con.prepareStatement("select*from Student where id='"+Integer.parseInt(id.getText())+"'");
              rst = com.executeQuery();
              
              if(rst.next()){
                   JOptionPane.showMessageDialog(null, "رقم الطالب موجود مسبقا","موجود",2);
                  
              }else{
                  com = con.prepareStatement("Insert into Student values('"+Integer.parseInt(id.getText())+"','"+name.getText()+"','123','"+mobile.getText()+"','"+gender+"','0','0','0','0')");
                   com.execute();
      
        JOptionPane.showMessageDialog(null, "تم اضافة الطالب بنجاح","تمت الاضافة",JOptionPane.INFORMATION_MESSAGE);
        Clear();
                      
              }
              
          } catch (SQLException ex) {
          }finally{
              con.close();
          }
          
      }else{
       JOptionPane.showMessageDialog(null,miss,"فقد بيانات الدخول",2); 
      }
    }

    private void Update() {
       String miss = "لقد نسيك ادخال البيانات التاليه"+"\n";
     
      
      if(name.getText().equals("")){
          miss+="اسم الطالب"+"\n";
      }
      if(mobile.getText().equals("")){
          miss+="رقم الجوال"+"\n";
      }
      if(!male.isSelected()&&!fmale.isSelected()){
          miss+="الجنس"+"\n";
      }  
      String gender=male.getText();
      if(fmale.isSelected()){
          gender = fmale.getText();
      }
      
      
        
      if(!name.getText().equals("")&&!mobile.getText().equals("")&&(male.isSelected()||fmale.isSelected())){   
           try {
               con=ConnectionDataBase.Connet();
               com = con.prepareStatement("Update Student set nameS='"+name.getText()+"',mobile='"+mobile.getText()+"',gender'"+gender+"'where id='"+Integer.parseInt(id.getText())+"' ");
               com.execute();
               JOptionPane.showMessageDialog(null,"تم تعديل الطالب بنجاح","تم التعديل",JOptionPane.INFORMATION_MESSAGE);
               Clear();
               id.setEnabled(true);
               name.setEnabled(false);
               mobile.setEnabled(false);
               male.setEnabled(false);
               fmale.setEnabled(false);
               
           } catch (SQLException ex) {
           
           }finally{
               try {
                   con.close();
               } catch (SQLException ex) {
                
               }
           }
      } else{
      JOptionPane.showMessageDialog(null,miss,"فقد بيانات الدخول",2);    
      }
    }

    private void Delete() {
         String miss = "لقد نسيك ادخال البيانات التاليه"+"\n";
        if(id.getText().equals("")){
          miss+="رقم الطالب"+"\n";
      }
      if(!id.getText().equals("")){   
      JOptionPane.showMessageDialog(null, "wellcom");}
      else{
      JOptionPane.showMessageDialog(null,miss,"فقد بيانات الدخول",2);    
      }
        
    }

    private void Clear() {
        id.setText("");
        name.setText("");
        mobile.setText("");
        
    }
}
